//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace booksQuotesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Quote
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Quote")]
        [StringLength(250)]
        public string QuoteText { get; set; }

        
        [Display(Name = "Image URL")]
        public string ImageURL { get; set; }

        public Nullable<int> BookId { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
